### ISSUE TITLE
Unable to add the plugin to an Android project!

### ISSUE THREAD

**Issue by mohsenoid** [clarityai-eng/codeartifact-gradle-plugin#140]
I was trying to use this plugin in an Android app and facing this issue:
![image](https://user-images.githubusercontent.com/5135535/120801899-1245a680-c542-11eb-85f7-c2612b70459b.png)

I can see that this plugin is released on:
https://plugins.gradle.org/m2/ai/clarity/codeartifact/ai.clarity.codeartifact.gradle.plugin/

but I am not sure if Android Gradle uses the same repo!

any suggestion on how to fix it?

**Comment by jfisbein** [comment]
Hi @mohsenoid, sadly I'm not an Android developer, but the plugin is released in the official gradle central plugin repositories.
Exactly here: https://plugins.gradle.org/plugin/ai.clarity.codeartifact

Can you share your build.gradle file?

**Comment by mohsenoid** [comment]
Thanks for the reply, it isn't a special setup. I even tried it with a new Android project and it didn't work.
Looks like the Gradle in Android projects uses another repo to pull plugins or somehow ignores this one.

Feel free to close this issue, cause we switch to GitHub Packages instead of AWS CodeArtifact, cause it doesn't neet generating token OTG.

**Comment by jfisbein** [comment]
Thanks
